# docker-openresty .travis.yml
#
# Builds docker-openresty images on Travis CI
#
# https://travis-ci.com/neomantra/docker-openresty
#
#
# Master will build with Docker tag:
#   openresty:<flavor>
#
# Releases should be tagged in git as:
#   <openresty-version>-<docker-version>
#
# This will build with Docker tags:
#   openresty:<openresty-version>-<docker-version>-<flavor>
#   openresty:<openresty-version>-<flavor>
#

os: linux
dist: bionic
language: ruby

services:
  - docker

stages:
  - build
  - manifest

before_script:
  - echo $DOCKER_PASSWORD > /tmp/docker.pass

jobs:
  include:
    - name: build docker image for amd64 flavors alpine and alpine-fat
      stage: build
      arch: amd64
      script:
      - ./docker_build_and_push_flavor.sh alpine-amd64 alpine/Dockerfile
      - ./docker_build_and_push_flavor.sh alpine-fat-amd64 alpine/Dockerfile.fat

    - name: build docker image for arm64 flavors alpine and alpine-fat
      stage: build
      arch: arm64
      script:
      - ./docker_build_and_push_flavor.sh alpine-arm64v8 alpine/Dockerfile
      - ./docker_build_and_push_flavor.sh alpine-fat-arm64v8 alpine/Dockerfile.fat

    - name: build docker image for flavor alpine-apk
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh alpine-apk

    # aliased as `centos-rpm`
    - name: build docker image for flavor centos
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh centos
      - ./docker_tag_alias.sh centos centos-rpm

    - name: build docker image for amd64 flavor centos7
      stage: build
      arch: amd64
      script:
      - ./docker_build_and_push_flavor.sh centos7-amd64 centos7/Dockerfile

    - name: build docker image for arm64 flavor centos7
      stage: build
      arch: arm64
      script:
      - ./docker_build_and_push_flavor.sh centos7-arm64v8 centos7/Dockerfile


    - name: build docker image for flavor Amazon Linux (amzn2)
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh amzn2 centos/Dockerfile --build-arg RESTY_IMAGE_BASE=amazonlinux --build-arg RESTY_IMAGE_TAG=2 --build-arg RESTY_YUM_REPO="https://openresty.org/package/amazon/openresty.repo" --build-arg RESTY_RPM_DIST="amzn2"

    # also master buster gets tagged "latest"
    - name: build docker image for flavor buster and buster-fat
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh buster
      - ./docker_build_and_push_flavor.sh buster-fat buster/Dockerfile.fat
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin &&
          docker tag openresty:buster $DOCKER_ORG/openresty:latest &&
          docker push $DOCKER_ORG/openresty:latest ;
        fi

    - name: build docker image for flavor bionic
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh bionic

    - name: build docker image for flavor focal
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh focal

    # aliased as `fedora-rpm`
    - name: build docker image for flavor fedora
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh fedora
      - ./docker_tag_alias.sh fedora fedora-rpm


    - name: create and push manifests for multi-arch builds
      stage: manifest
      script:
      - ./docker_manifest.sh alpine      alpine-amd64  alpine-arm64v8
      - ./docker_manifest.sh alpine-fat  alpine-fat-amd64  alpine-fat-arm64v8
      - ./docker_manifest.sh centos7  centos7-amd64  centos7-arm64v8
